function [cons] = HMM_con(arg)


cons = struct( 's1', 2,...
              's2', 1,...
              's3', 1,...
              'tran_diag',0.3,...
              'alpha', 1,...
              'am', 5,...
              'rm', 0.3,...
              'J_c', 20,...
              's_c',1);
                